name: Deploy to Google cloud VM.

on:
  # Manual trigger only – nothing runs on push/PR
  workflow_dispatch:

env:
  VM_USER: ameau
  VM_HOST: 34.94.189.67
  PROJECT_DIR: /home/ameau/csca-5028-sentiment-analysis

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Build all JARs
        run: ./gradlew clean build -x test

      - name: Prepare SSH key (from repo file)
        run: |
          mkdir -p ~/.ssh
          cp .git/ssh-key.txt ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          printf 'Host *\n\tStrictHostKeyChecking no\n' > ~/.ssh/config

      - name: Copy all jars to VM
        run: |
          set -e

          echo "Copying component jars..."
          scp -i ~/.ssh/id_rsa \
            components/database/build/libs/database-1.0.0.jar \
            "${VM_USER}@${VM_HOST}:${PROJECT_DIR}/components/database/build/libs/database-1.0.0.jar"

          scp -i ~/.ssh/id_rsa \
            components/sentiment/build/libs/sentiment-1.0.0.jar \
            "${VM_USER}@${VM_HOST}:${PROJECT_DIR}/components/sentiment/build/libs/sentiment-1.0.0.jar"

          scp -i ~/.ssh/id_rsa \
            components/messaging/build/libs/messaging-1.0.0.jar \
            "${VM_USER}@${VM_HOST}:${PROJECT_DIR}/components/messaging/build/libs/messaging-1.0.0.jar"

          echo "Copying application jars..."
          scp -i ~/.ssh/id_rsa \
            applications/data-analyzer-server/build/libs/data-analyzer-server-1.0.0.jar \
            "${VM_USER}@${VM_HOST}:${PROJECT_DIR}/applications/data-analyzer-server/build/libs/data-analyzer-server-1.0.0.jar"

          scp -i ~/.ssh/id_rsa \
            applications/frontend-server/build/libs/frontend-server-1.0.0.jar \
            "${VM_USER}@${VM_HOST}:${PROJECT_DIR}/applications/frontend-server/build/libs/frontend-server-1.0.0.jar"

          scp -i ~/.ssh/id_rsa \
            applications/data-collector-server/build/libs/data-collector-server-1.0.0.jar \
            "${VM_USER}@${VM_HOST}:${PROJECT_DIR}/applications/data-collector-server/build/libs/data-collector-server-1.0.0.jar"

      - name: Restart app containers on VM
        run: |
          ssh -i ~/.ssh/id_rsa "${VM_USER}@${VM_HOST}" \
            "cd ${PROJECT_DIR} && docker compose restart frontend-server data-analyzer data-collector"

      - name: Cleanup SSH key
        if: always()
        run: rm -rf ~/.ssh

